name: flutter_ext
description: Flutter utility extensions for Adsplatter.
version: 1.0.0
repository: https://github.com/adsplatter/flutter-ext
homepage: https://github.com/adsplatter/flutter-ext
issue_tracker: https://github.com/adsplatter/flutter-ext/issues

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
